#! /bin/bash

# move-and-symlink
#
# Move a file (potentially between filesystems), and leave a symlink to
# the old location in its place.
#

set -e

if [[ $# -lt 2 ]]; then
	echo "Usage: $0 <old location> <new location>"
	exit 1
fi

ALPHA=$1
OMEGA=$2

# If we're given an existing target directory, create a link inside it.
if [[ -d $OMEGA ]]; then
	OMEGA="${OMEGA}/$(basename $ALPHA)"
fi

cp -an $ALPHA $OMEGA
rm -r $ALPHA
ln -s $OMEGA $ALPHA
