#! /bin/bash

# move-and-symlink
#
# Move a file (potentially between filesystems), and leave a symlink to
# the old location in its place.
#

set -e

if [[ $# -lt 2 ]]; then
	echo "Usage: $0 <old location> <new location>"
	exit 1
fi

ALPHA=$1
OMEGA=$2

if [[ -e $OMEGA ]]; then
	echo "${OMEGA} already exists; bailing out."
	exit 1
fi

cp -an $ALPHA $OMEGA
rm -r $ALPHA
ln -sfT $OMEGA $ALPHA
